function ensureSheet_(ss,name,header){let sheet=ss.getSheetByName(name);if(!sheet)sheet=ss.insertSheet(name);if(sheet.getLastRow()===0){sheet.getRange(1,1,1,header.length).setValues([header]);sheet.setFrozenRows(1);return sheet;}const current=sheet.getRange(1,1,1,Math.max(sheet.getLastColumn(),header.length)).getValues()[0].map(String);header.forEach(function(label,index){if(current.indexOf(label)>=0)return;sheet.insertColumnBefore(index+1);sheet.getRange(1,index+1).setValue(label);current.splice(index,0,label);});sheet.setFrozenRows(1);return sheet;}
function indexHeader_(header){const out={};header.forEach(function(label,index){out[String(label||'').trim()]=index;});return out;}
function value_(row,index){return index===undefined||index===null?null:row[index];}
function parseDate_(value){if(!value)return null;const d=value instanceof Date?value:new Date(value);return isNaN(d.getTime())?null:d;}
function truthy_(value){return value===true||String(value).toLowerCase()==='true'||Number(value)===1;}
function finitePositive_(value){return isFinite(Number(value))&&Number(value)>0;}
function usdToSats_(usd,btc){return finitePositive_(btc)?Number(usd)/Number(btc)*100000000:null;}
function median_(values){const rows=values.map(Number).filter(isFinite).sort(function(a,b){return a-b;});if(!rows.length)return NaN;const m=Math.floor(rows.length/2);return rows.length%2?rows[m]:(rows[m-1]+rows[m])/2;}
function numberFrom_(value){if(typeof value==='number')return value;const n=Number(String(value||'').replace(/[^0-9.]/g,''));return isFinite(n)?n:NaN;}
function parseQuantity_(title){const text=String(title||'').toLowerCase();const patterns=[[/([0-9]+(?:\.[0-9]+)?)\s*(lb|lbs|pound|pounds)\b/,'lb'],[/([0-9]+(?:\.[0-9]+)?)\s*(oz|ounce|ounces)\b/,'oz'],[/([0-9]+(?:\.[0-9]+)?)\s*(gallon|gallons|gal)\b/,'gallon'],[/([0-9]+(?:\.[0-9]+)?)\s*(gram|grams|g)\b/,'gram'],[/([0-9]+(?:\.[0-9]+)?)\s*(count|ct)\b/,'count'],[/([0-9]+(?:\.[0-9]+)?)\s*(kwh)\b/,'kwh']];for(let i=0;i<patterns.length;i++){const match=text.match(patterns[i][0]);if(match)return{quantity:Number(match[1]),unit:patterns[i][1]};}if(/dozen/.test(text))return{quantity:12,unit:'count'};return{quantity:NaN,unit:''};}
function normalizeUnit_(unit){const x=String(unit||'').toLowerCase();if(/^(lb|lbs|pound)/.test(x))return'lb';if(/^(oz|ounce)/.test(x))return'oz';if(/^(gram|g)$/.test(x))return'gram';if(/^(gallon|gal)/.test(x))return'gallon';if(/^(count|ct)/.test(x))return'count';if(/kwh/.test(x))return'kwh';return x;}
function addQuery_(url,key,value){return url+(url.indexOf('?')>=0?'&':'?')+encodeURIComponent(key)+'='+encodeURIComponent(value);}
function slug_(value){return String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'');}
function emptyDashboard_(active,props){const core=active.filter(isCoreItem_),now=new Date();return{version:PP_VERSION,generatedAt:now.toISOString(),basketDefinition:{method:'fixed_quantity_total',itemCount:core.length,items:core.map(publicItem_),referencesExcluded:REFERENCE_IDS},snapshots:[],itemSeries:[],references:{},quality:emptyQuality_(core.length),reliability:buildReliability_([],[],core.length,props&&props.serpApiMaxSearchesPerDay||6,now,props&&props.reliabilityStartDate||'2026-09-01')};}
